# Generated by Django 4.2 on 2025-07-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_client_commande_materiel_min_quantite_materiel_prix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materiels/'),
        ),
    ]
