# Generated by Django 4.2 on 2025-07-08 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_commande_commercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='comerciale',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
