# Generated by Django 4.2 on 2025-07-11 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_commande_comerciale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='materiel',
        ),
        migrations.AddField(
            model_name='installation',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.commande'),
        ),
    ]
