# Generated by Django 4.2 on 2025-07-12 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_installation_materiel_installation_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dernier_commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dernier_commercial', to=settings.AUTH_USER_MODEL)),
                ('dernier_technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dernier_technicien', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
