# Generated by Django 4.2 on 2025-07-16 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_preparercommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationutilisateur',
            name='dernier_coursier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dernier_coursier', to=settings.AUTH_USER_MODEL),
        ),
    ]
