# Generated by Django 4.2 on 2025-07-16 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_affectationutilisateur_dernier_coursier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursierCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.preparercommande')),
                ('coursier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
