# Generated by Django 4.2 on 2025-07-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_coursiercommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursiercommande',
            name='Commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.commande'),
        ),
    ]
