# Generated by Django 4.2 on 2025-07-17 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_coursiercommande_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienCommandeAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis', models.CharField(max_length=120)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.commande')),
            ],
        ),
    ]
