# Generated by Django 4.2 on 2025-07-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_cliencommandeavis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliencommandeavis',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.client'),
        ),
    ]
